### ISSUE TITLE
Maximize big-cloud node

### ISSUE THREAD

**Issue by ericleasemorgan** [ericleasemorgan/reader#111]
Please maximize the number of big-cloud partitions at our disposal.

I believe we no longer have a real need for the nodes (partitions) named cloud, and instead, we could use additional partitions named big-cloud. 

Moreover, I believe you created a node intended to host a database, but I do not think we need that anymore.

If it not being used, please delete the node intended for the database, and then redeploy all of our remaining resources to create as many big-cloud partitions as possible. 

When this is done, I think we will have a single head node, a single HTTP node, at least a couple Solr nodes, and the balance can be partitions called big-cloud.

'Make sense?

**Comment by ECoulter** [comment]
This is done, as of today! :)
