### ISSUE TITLE
Build cord database using SolrCloud

### ISSUE THREAD

**Issue by ralphlevan** [ericleasemorgan/reader#117]
Using the same schema that Art uses, build the cord database using the SolrCloud array built on the solr nodes provided to us (solr-master and solr-worker, soon to be renamed solr-01 and solr-02)

**Comment by ericleasemorgan** [comment]
I think this has been done too, otherwise I would not have been able to complete #118

**Comment by ralphlevan** [comment]
Indeed! It will be the first thing I mark off.
Ralph

**Comment by ralphlevan** [comment]
Eric, you can't close this until the paperwork is done! We need a pull request to get the new files controlled. Once the pull request is acted on, this issue should be closed automagically
