### ISSUE TITLE
Use the new SolrCloud in the Reader

### ISSUE THREAD

**Issue by ralphlevan** [ericleasemorgan/reader#118]
When Ralph or Art tell you that the cord database is available in the SolrCloud array, change the hostname that Reader currently uses to access the database to either solr-master or solr-01. The uncertainty in the name is because Eric C. is in the process of changing the original, non-scaling, names to the new names. It's my belief that if the database was built right, this will be the only change necessary.

**Comment by ericleasemorgan** [comment]
Okay. I will wait until Ralph or Art "tell me".  :-)

**Comment by ericleasemorgan** [comment]
I think I finished this today; today I configured my scripts to search against http://solr-01:8983/solr/cord. It feels good to "cross items off" in the to-do list!

**Comment by ralphlevan** [comment]
Congrats! I should go out and see if there are things i can remove.

Ralph
