### ISSUE TITLE
Update IU 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#120]
on https://cord.distantreader.org/ change all the "University of Indiana" text to "Indiana University"  @ECoulter maybe you or shivam or sudhakar can update this ? And double check it's okay elsehwere in public facing pages? 

![image](https://user-images.githubusercontent.com/3044754/85925529-f97b3e00-b866-11ea-8022-541325a24b12.png)

**Comment by ericleasemorgan** [comment]
Yep, embarrassing. Fixed.
