### ISSUE TITLE
add nav and style to /export/reader/www/external/index.html

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#123]
Add add nav and style to` /export/reader/www/external/index.html` which resolves as [https://cord.distantreader.org/](https://cord.distantreader.org/)

Make sure top of page carries distant reader branding and that users on this page can easily navigate to carrels, contributor info, etc 
![image](https://user-images.githubusercontent.com/3044754/85954279-3ff29a80-b944-11ea-8473-c747095dfba8.png)

Include this stuff too if  appropriate 
![image](https://user-images.githubusercontent.com/3044754/85954360-e2128280-b944-11ea-93ec-935117eab189.png)

**Comment by dbrower** [comment]
Copied the nav bar from the main site to the CORD-19 site. I'll figure out the links, especially the social media and github links, next.

**Comment by dbrower** [comment]
Closing this issue since the new webui removes all the various subdomains. And the new "contact us" page can have links to social media things (thought I don't think we decided to display any at the moment).
