### ISSUE TITLE
enhance provenance file to include real & true data/time values, as well as version of the CORD database

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#124]
check whether in carrels provenance.tsv  file is always written with  values  like <carrelname> 2020-05-28 12:00 <user><query> where date time always = 2020-05-28 12:00 no matter when the SOLR query to make-carrel was run or the  provenance file was created?  or is it just a freaky coincidence?

**Comment by ericleasemorgan** [comment]
Our provenance file is a tab-delimited file containing the carrel's short name, date, time, email address of creator, and the query used against CORD database. This file needs to be enhanced to include a version date/number of the CORD database when the file came. This file also needs to have the real and true value of the date and time.

**Comment by ericleasemorgan** [comment]
The current date and time a carrels was created is now a part of the provenance file, and when the carrel is created this date and time appear on the carrel's home page. This particular task is done, but now we need to added a CORD version stamp. That is a different "issue". Closing.
