### ISSUE TITLE
Add Sign in to Signup

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#136]
that'll go to authenticate via orcid 
here's an example:
![image](https://user-images.githubusercontent.com/3044754/114722657-fa9f2e00-9d07-11eb-81dc-4cf4a33e8e40.png)

**Comment by dbrower** [comment]
We wouldn't ask for a username or password on our site since ORCID is doing the authentication.

I wonder whether we need a sign-in page at all. what if we just redirected people to the ORCID page? One downside is that people might be confused if they didn't know we were using ORCIDs for sign-in.

**Comment by dbrower** [comment]
Finished. See https://distantreader.org/p/login
