### ISSUE TITLE
Use this to update tagline on front page:

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#137]
Here's some content for the tagline

"Intended for anybody who reads, the Distant Reader takes text as input, does analysis against it, and outputs sets of structured data, affectionately called "study carrels". The student, research, or scholar can then use a study carrel to read the text both closely as well as at a distance."

**Comment by ericleasemorgan** [comment]
@nkmeyers, that looks great to me. @randal-sean-harrison, please use Natalie's text as your first draft. Feel free to "season to taste".

**Comment by dbrower** [comment]
I think the home page text has been updated.  https://distantreader.org/p
