### ISSUE TITLE
Remove apache password access (in favor of orcid)

### ISSUE THREAD

**Issue by dbrower** [ericleasemorgan/reader#138]

**Comment by dbrower** [comment]
PR:  ericleasemorgan/reader-classic/pull/23

**Comment by ericleasemorgan** [comment]
Ironically, and the past few days, I have received a few password requests, and I have granted them. If I "pull the trigger" and commit PR #23, then will these new Reader users be unable to authenticate?

**Comment by dbrower** [comment]
This only applies to the `/p/` pages. I'm not planning on making the `/p/` pages the main site until some other things get looked at, like the email validation (#141 ) and having a way for people to view their carrels without using a password.

**Comment by dbrower** [comment]
> Ironically, and the past few days, I have received a few password requests, and I have granted them. If I "pull the trigger" and commit PR #23, then will these new Reader users be unable to authenticate?

Oh, and yes. I thought we agreed that associating ORCIDs with existing accounts was not desired. So whenever the ORCIDs get added to the main site, these people would essentially have new accounts.

**Comment by dbrower** [comment]
@ericleasemorgan Would you like to leave the password option around for a little while longer? It would be easy to put back. And I would keep all the new ORCID sign-ins as creating new accounts.
