### ISSUE TITLE
Support "My Carrels" API access

### ISSUE THREAD

**Issue by dbrower** [ericleasemorgan/reader#139]
The UI needs an endpoint to get a list of all the carrels owned by the current user.

@randal-sean-harrison

**Comment by ericleasemorgan** [comment]
@dbrower, what do you need from me to accomplish this goal?

**Comment by dbrower** [comment]
I think the app can look at the directories in the user's section on `/data-disk/`, at least for now.

it might be a two step process where the data gets harvested and stuck in the main sqlite database.

**Comment by dbrower** [comment]
I think this ticket is moot since it was just to support a way to display all the public carrels. A public carrel page has been added to the webui.
