### ISSUE TITLE
create an indexer node, and initialize an index

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#14]
related to #15

**Comment by ericleasemorgan** [comment]
I think y'all are one your way on this one.

**Comment by ericleasemorgan** [comment]
Art and Ralph, now that a Solr index has been created, please make it run on the designated Solr node. Okay?

**Comment by ralphlevan** [comment]
I think @ericleasemorgan is guilty of feature creep! Art has satisfied the initial requirement of building an index. I'm going to close this issue and open two new ones. The first will be to get Solr Cloud running on the designated nodes and the second will be to point the reader at the new Solr Cloud.
