### ISSUE TITLE
Create log in page

### ISSUE THREAD

**Issue by ericleasemorgan** [ericleasemorgan/reader#147]
@randal-sean-harrison needs to take @dbrower's good ORCID work, and use it as a framework for creating log in page.

**Comment by dbrower** [comment]
[The template](https://github.com/ericleasemorgan/reader-classic/blob/master/webui/templates/login.html) for the not-quite-current, but soon-to-be login page.

**Comment by nkmeyers** [comment]
@randal-sean-harrison 
 the login page works but renders kinda wonky
 - needs some padding on main pane at left ? 
 - Weight/size of footer is disproportionate to main pane? 
 
Login using ORCID and 
Sign in with ORCID button with black outline 
render so similarly that it is hard to tell which is the label and which is the button? 

can we maybe copy this sign in pane layout approach at ORCID? 
https://orcid.org/signin

![image](https://user-images.githubusercontent.com/3044754/119171019-05995c80-ba32-11eb-83ab-af66afa98912.png)

![image](https://user-images.githubusercontent.com/3044754/119170561-6aa08280-ba31-11eb-96aa-98c12f1a2fff.png)

**Comment by nkmeyers** [comment]
there's also code for a simple UI for obtaining authenticated ORCID iDs using OAuth with OpenID Connect https://github.com/ORCID/orcid-auth-widget

**Comment by dbrower** [comment]
> there's also code for a simple UI for obtaining authenticated ORCID iDs using OAuth with OpenID Connect https://github.com/ORCID/orcid-auth-widget

Thanks Natalie! This looks like it is for a single-page javascript app, though. And we can't have the image with the username and password, since it is ORICD that is doing the authentication.

What if the sign-in button were restyled to be clearer, similar to how websites have a "sign-in with Google" button?

**Comment by nkmeyers** [comment]
@dbrower yeah, I was thinking we just lift this part and change the text to be "sign in via orcid" and a companion "regsiter/get your orcid" for people who don't have one?

Just these two buttons and the text link to go get one if you don't have one? 

![image](https://user-images.githubusercontent.com/3044754/119179879-785c0500-ba3d-11eb-962b-8fdf2ad48004.png)

**Comment by dbrower** [comment]
Finished. See https://distantreader/p/login
