### ISSUE TITLE
Create a catalog of public study carrels

### ISSUE THREAD

**Issue by ericleasemorgan** [ericleasemorgan/reader#149]
We want to create an interactive list of public study carrels.

There is a JSON file containing rudimentary descriptions of each public carrel, and it is located at https://library.distantreader.org/catalog/catalog.json   Please use this file as input, and output some sort of table enabling people to search/browse the collection as well as read, browse, and download carrels. That last bit may be a bit tricky, and please give it a go, and we'll work on the last bit in a... bit.

**Comment by dbrower** [comment]
The JSON is an array of objects, each object having a structure similar to the following.

```json
{
    "shortname": "bahnemann-transforming-2021",
    "date-created": "2021-01-24",
    "keywords": "oclc, link, Wikibase, Metadata, Library",
    "items": "1",
    "words": "21,338",
    "flesch": "44",
    "size": "33,066,178"
}
```

Some of these values could be adjusted to be more friendly for machine use.
1) Can we remove the commas from the numbers in `items`, `words`, `flesch`, and `size`? They make it more difficult for code to sort by that field.
2) Should the list of keywords be a json array of strings instead? (and note the commas here have a different role (separating) than the commas in the numbers. Humans have no problem with this, but...)

If we decide to do this, I can make these changes with the `jq` tool.

**Comment by dbrower** [comment]
Is the API needed for itself? Or is it a means to having a public carrel listing? If the latter we can close this issue since I have added a public carrel page to the webui.

**Comment by dbrower** [comment]
I'm going to close this ticket since there is a catalog of public carrels in the new UI. If an API is needed, that can be a new ticket.
