### ISSUE TITLE
can't login to see carrels 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#153]
I can't login and have two user accounts now(nmeyers and nkmeyers) I think after authenticating via orcid. 
I can't see my carrel output, for example:
https://library.distantreader.org/patrons/nkmeyers/elsingleissue/ (user nkmeyers authenticated via orcid)
I can see this carrel output 
https://library.distantreader.org/patrons/nmeyers/Arnaud1article/ (user nmeyers authenticated via distant reader )

**Comment by nkmeyers** [comment]
Also No way to sign out once authenticated via orcid -it's like the Hotel California, you can check in but never leeeeave 
![image](https://user-images.githubusercontent.com/3044754/118878245-576ca600-b8bd-11eb-8101-fa003efdfc3c.png)

**Comment by dbrower** [comment]
Yeah, there are a few loose ends. 😄   Specifically, no way to log out. I will add a sign out button. until then you can "sign out" by deleting the site cookie.

The stuff on library.distantreader.org is using the Apache auth. It will be phased out. Apparently one place where links need to be updated is in the emails sent from the compute side of the code. Thanks for finding this.

What do you see if you choose the "browse your carrels" in the drop down? 

Also, I can unify your two accounts in the database. I was told to not plan for old accounts to transition to the ORCID log in. I'll send you an email when I do it.

**Comment by nkmeyers** [comment]
From 5/19/2021
![image](https://user-images.githubusercontent.com/3044754/119026034-b809ea80-b972-11eb-8e05-dcfbd0952429.png)

**Comment by nkmeyers** [comment]
This problem is "Solved"  @dbrower , ok to close? 

![image](https://user-images.githubusercontent.com/3044754/119170408-33ca6c80-ba31-11eb-8eeb-ec010f32647f.png)

**Comment by dbrower** [comment]
Great! And I added a sign-out link.
