### ISSUE TITLE
integrate public carrels landing page 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#154]
integrate public carrels landing page view currently at: https://library.distantreader.org/catalog/ into distantreader.org repo and domain so it can use the same login and skin and users stay in one environment.  Else re-skin https://library.distantreader.org/catalog/ but that's sub-optimal because users "lose" their login and access to their own stuff?

**Comment by dbrower** [comment]
The page at https://library.distantreader.org/catalog/ only shows the public carrels. Eric has do to a manual process to make them public. Users cannot "lose" their carrels on this page.

Once the private carrels are working 100%, it should be little effort to move the public carrels to the new UI.

**Comment by dbrower** [comment]
This issue is related to #149

**Comment by randal-sean-harrison** [comment]
I’m a fair bit farther than the middle of making changes, but I don’t want to push my changes until I chat with you, Don. 

Want to set an appt for this afternoon, if we can? 

Cheers,
Randy

Randal Sean Harrison, Ph.D.
Associate Librarian, Emerging Technologies
Hesburgh Libraries

Concurrent Teaching Professor, Management & Organization
Mendoza College of Business

University of Notre Dame
158 Hesburgh Library
Notre Dame, IN 46556

(574) 631-0312
***@***.*** ***@***.***>
randalseanharrison.com <https://randalseanharrison.com/>

⌖  Map to my office <https://randalseanharrison.com/img/map-to-my-office.svg>
⌖  Meet with me <https://calendly.com/randal-sean-harrison/consultation>

**Comment by dbrower** [comment]
I merged in a public carrel page listing.
