### ISSUE TITLE
About page  - Resurrect "Cite Distant Reader" 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#155]
Need to Resurrect Cite Distant reader blurb onto "[About Us" Page]() or a separate landing page. 

Also need to up-version the content and blurb on zenodo to create viable content for the "Cite Distant Reader" blurb 
Also need to in the citation or About statement document  the different code repos for distant reader (what is required for all the DR features to "work" ) and what the code in the other different reader repos(11? 12? )  related to distant reader do? 

The first citation created against code deposited on zenodo was :

Morgan, Eric Lease. (2020, April 10). Distant Reader (Version Alpha). Zenodo. http://doi.org/10.5281/zenodo.3747777 
That landing page states :

> The Distant Reader is a high performance computing (HPC) system which takes an almost arbitrary amount of unstructured data (text) as input and outputs a set of structured data for analysis -- "reading".
> 
> currently being developed at:  https://github.com/ericleasemorgan/reader
> 
> currently published at: https://distantreader.org/ 

But maybe some of that code or the current development is at distant reader classic? If so, we need to do an update and/or new citation or both and explanation about where the currently active code base is ? 

There's a second zenodo record that I'm not sure what github code base it points to? It is  at: 
Eric Lease Morgan, & David Molik. (2020, April 11). ericleasemorgan/reader: Zendo Release (Version zendo). Zenodo. http://doi.org/10.5281/zenodo.3748661 [I don't think we want to upversion this one]

**Comment by dbrower** [comment]
I can add the old citation, but maybe @ericleasemorgan wants to make a newer one?

**Comment by dbrower** [comment]
Please look at the bottom of https://distantreader.org/p/about and comment whether it is the correct citation.
