### ISSUE TITLE
create a node for serving HTTP

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#16]

**Comment by ericleasemorgan** [comment]
Eric C. Please create YAN -- Yet Another Node. This one will also be a small node, and will be a tiny HTTP server, but it will do zero CGI.

**Comment by ericleasemorgan** [comment]
Eric C, how goes the work in this regard? Please create a node just like the dr-web2. Okay?

**Comment by ECoulter** [comment]
Eric M - Sorry for the delay; this is done! Still need to create the cert; sent IP info in slack. 
Created /export/www on the cov19-headnode, and mounted the same on the web node.

**Comment by ECoulter** [comment]
This is done fully - certs are up and the DNS entry is
cord.distantreader.org
