### ISSUE TITLE
carrel columns can't order by date

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#172]
Is there a way to make the "browse my carrels" column display sortable by date with most recently created carrel at top or make that the default sort? It is awkward to read them in alpha order.  For example in https://distantreader.org/p/patrons/nmeyers/ can i sort my carrels by date or could that be the default sort?

**Comment by ericleasemorgan** [comment]
> Is there a way to make the "browse my carrels" column display sortable by date with most recently created carrel at top or make that the default sort? It is awkward to read them in alpha order. For example in https://distantreader.org/p/patrons/nmeyers/ can i sort my carrels by date or could that be the default sort?

N-, yes, click on any column heading to sort in a whole bunch of different ways. --ELM

**Comment by nkmeyers** [comment]
Umm - nope, not in that view, those columns don't click or sort? 
If you click this 
![image](https://user-images.githubusercontent.com/3044754/120387536-0a92c180-c2f8-11eb-90a8-4f75ef4941a2.png)
then the view you get next: [https://distantreader.org/p/patrons/**username**/  ](https://distantreader.org/p/patrons/nmeyers/) does not have sortable columns ?

**Comment by nkmeyers** [comment]
The search box that's mentioned does not appear either 

![image](https://user-images.githubusercontent.com/3044754/120388038-9efd2400-c2f8-11eb-9273-c6667a601e26.png)

**Comment by nkmeyers** [comment]
The features for "public carrels" do not appear on the "browse my carrels" aka user's carrels page 

this stuff is not on those pages 
![image](https://user-images.githubusercontent.com/3044754/120388282-e84d7380-c2f8-11eb-9381-fa4f3cf55a84.png)

**Comment by dbrower** [comment]
Yeah, the public and private carrel listings are different, and the goal is to make them behave the samee, like the public carrels currently are. Thanks for submitting this issue, @nkmeyers .

**Comment by dbrower** [comment]
One can now sort private carrels by date.
