### ISSUE TITLE
No search box on Create Carrel cord? main pane 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#173]
Hi
The CORD19 to study carrel Create Carrel link goes to /p/cord? but the main pane there does not have a search box? 
There's just a search button but no place to put input? 

need to add an input box and tidy the text instructions they are weird:

> Use these pages to search the CORD data set and possibly queue the creation of study carrels.
> 
> Enter a query.

![image](https://user-images.githubusercontent.com/3044754/120714803-b3285900-c491-11eb-8116-1fff7e1fa83a.png)

**Comment by dbrower** [comment]
The query box has been reappeared.
