### ISSUE TITLE
Browse my carrels needs padding and header footer re-style 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#174]
Browse my carrels page (aka /patrons/username/ page) needs pane padding - search box runs into side of page etc and page needs restyle header and footer  @randal-sean-harrison 

![image](https://user-images.githubusercontent.com/3044754/120716044-7c534280-c493-11eb-9f56-e15c3a2b7e14.png)

**Comment by dbrower** [comment]
Closing since the carrel browse page is now padded.
