### ISSUE TITLE
User browse carrel resolve to index.htm?

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#176]
Could/should  target of Users' Browse Carrel click action be to render the carrel's index.htm page ? 

The options have to have meaning for first time users that do not contradict their notions of what "read", "browse" mean on other systems? 

I wonder would "view", "directory" and "download" be better action labels than "browse" "read" "download" at the users' carrels' directory/ list level?

I think here in the UI  is where the carrel vernacular breaks down a bit and index.htm isn't a default render me first for the stuff in the directory - the reader webui steps away from notion of how a webserver typically serves output from a http accessible directory? 

for example if I select Browse on my wastewater carrel 
it resolves to https://distantreader.org/p/patrons/nmeyers/Wastewaterjune042021/ could it resolve to 
https://distantreader.org/p/patrons/nmeyers/Wastewaterjune042021/index.htm ? and a link to view the carrel directory be provided as another option labeled "directory"? 
![image](https://user-images.githubusercontent.com/3044754/121537677-1d7d5400-c9d2-11eb-8ed8-b234f27c5606.png)

**Comment by dbrower** [comment]
"Read" links to the carrel's index.htm page. As far as I know Browse links to the directory view.

I swapped the order of Browse and Read to make something else easier. Should I swap them back?

**Comment by dbrower** [comment]
I like changing the terminology. "view", "directory", "download" is better. I also get confused what Read and Browse mean

**Comment by dbrower** [comment]
Or "View", "Files", "Download"?  Is 'directory' too technical? not sure.

**Comment by dbrower** [comment]
I did the latter, feel free to reopen if you prefer something else.
