### ISSUE TITLE
column headers don't sort on carrel dir page

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#178]
For me on chrome column headers don't sort on "browse carrel page"  & what the rank order is, is not clear but for whatever reason index.htm is at the bottom and can't order by name or other header labels. Default Rank is not type or alpha bcs the folders don't stack and dir items list doesn't stack alpha. 

![image](https://user-images.githubusercontent.com/3044754/121552286-59b6b180-c9de-11eb-82e9-666d9544ee8c.png)

**Comment by dbrower** [comment]
File list sorting has been added.
