### ISSUE TITLE
gutenberg submission is missing provenance

### ISSUE THREAD

**Issue by ericleasemorgan** [ericleasemorgan/reader#183]
When a Project Gutenberg carrel is requested for creation, I believe the provenance file is not updated correctly. I last field has no value, and that value is a query string used to search the underlying index. This results in empty Gutenberg carrels.

**Comment by ericleasemorgan** [comment]
Don, will you please see if you can resolve this issue?

**Comment by dbrower** [comment]
fixed and deployed.
