### ISSUE TITLE
layout of top banner on home page is squishing the art 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#187]
The layout of the top banner on the home page is squishing the art - 
If you know what size you want the banner art we can ask Kristina to re-work the dimensions to suit. As currently cropped/resized it sort of eats too far into her graphic design? 

![image](https://user-images.githubusercontent.com/3044754/123474399-e4df9c00-d5c7-11eb-9120-38d6dbdacd01.png)

![distant-reader_banner (1)](https://user-images.githubusercontent.com/3044754/123474508-10fb1d00-d5c8-11eb-93df-55eedfc14f43.jpg)

**Comment by dbrower** [comment]
I could reproduce this by scaling my browser window down to 10% size.

The "squishing" looks to be a side-effect of scaling the image to be the full width of the window. When the window is very wide (at the 10% setting my browser window has a logical width of ~4000 px), the image scales to be very tall. But the jumbotron element that it is inside has no text, so it is set to a minimum height of 350px and hence the image gets cut short.

Any ideas @randal-sean-harrison ?

**Comment by dbrower** [comment]
To fix the problem, the image was made non-streachy. This should keep it from getting cropped funny on very wide windows.
