### ISSUE TITLE
create an API for interacting with the Distant Reader's structured data

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#19]
write a few applications demonstrating the use of the API; for example, 1) write a program to answer Kaggle or TREC-style challenges, or 2) take as list of identifiers as input and output reports based on the associated structured data

**Comment by ericleasemorgan** [comment]
While there is not an API, there are a number of tools for doing this sort of work, and they reside in  a couple of different repositories:

   1. https://github.com/ericleasemorgan/reader-extras
   2. https://github.com/ericleasemorgan/reader-workshop

**Comment by ericleasemorgan** [comment]
This has been subsumed into #98. While there will be no API, there will be a bunch o' script which will interact with downloaded study carrels.
