### ISSUE TITLE
enhance the Web-based full text index interface to output subsets of the data and supply them as input to the Distant Reader

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#20]
See #14 #15

**Comment by ericleasemorgan** [comment]
We can consider this "done". For example, one can "tunnel" to our head node:

`ssh -L 127.0.0.1:8080:localhost:8080 cord.distantreader.org`

You can then use your browser to interact with the index:

  http://localhost:8080

From there you can search the index and queue a study carrel for initialization and creation.
