### ISSUE TITLE
loop through the database to create a full text index of all of CORD-19

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#22]
relies on #15

**Comment by ericleasemorgan** [comment]
This is "done". I have created a database (but it requires regular refreshing). Art & Ralph have indexed it. I have created a Web-based interface to the whole. To use it, you must tunnel to one of our machines:

`ssh -L 127.0.0.1:8080:localhost:8080 cord.distantreader.org`

You then use your browser to interact with the index: http://localhost:8080
