### ISSUE TITLE
Create tickets for all this stuff 

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#26]
Create tickets for all this stuff below ( https://docs.google.com/document/d/1WZR1x1vUCYffXNlcs7Oe7q2UTfmFVM2zw3bnXD60MVc/edit )  in https://github.com/ericleasemorgan/reader/issues

**Comment by nkmeyers** [comment]
@molikd - some/most the stuff on this ticket-ifying  list isn't all for the CORD19 effort (doesn't rightfully belong in that "project", instead can just be general issues, or part of another project called enhancements or something?). Keep 'em separated?

**Comment by molikd** [comment]
Possibly another project?On Apr 15, 2020 2:10 PM, Natalie Meyers <notifications@github.com> wrote:
@molikd - some/most the stuff on this ticket-ifying  list isn't all for the CORD19 effort (doesn't rightfully belong in that "project", instead can just be general issues, or part of another project called enhancements or something?). Keep 'em separated?
