### ISSUE TITLE
add CDS branding to distantreader.org

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#3]
Eric, in the top left of [distantreader.org](https://distantreader.org/) you have the ND logo, would it be possible to put the Navari Center Digital Scholarship logo next to it. 

I should note that I don't actually think that the CDS has a logo, but the [cds.library.nd.edu](https://cds.library.nd.edu/) header "NAVARI FAMILY CENTER for DIGITAL SCHOLARSHIP" can be recreated exactly with the following css:

```
font-family: GPCBook,"HelveticaNeue",Helvetica,Arial,Verdana,sans-serif;
text-shadow: 1px 1px 1px rgba(0,0,0,.5);
text-rendering: optimizeLegibility;
font-style: normal;
direction: ltr;
font-weight: normal;
```

That first font family is GalaxiePolarisCondensed-Book and would have to be imported.

**Comment by ericleasemorgan** [comment]
> Eric, in the top left of distantreader.org you have the ND logo, would it be possible to put the Navari Center Digital Scholarship logo next to it.

Yes, I think so.

That logo is not really a part of the Reader; there is no repository for the HTML which creates the content at http://distantreader.org  Instead, when a person with the proper credential logs into the Reader, then a "kewl" link appears, and one can begin to edit the interface. I believe we can edit the logo accordingly.


> I should note that I don't actually think that the CDS has a logo, but the cds.library.nd.edu header "NAVARI FAMILY CENTER for DIGITAL SCHOLARSHIP" can be recreated exactly with the following css:
> 
> font-family: GPCBook,"HelveticaNeue",Helvetica,Arial,Verdana,sans-serif;
> text-shadow: 1px 1px 1px rgba(0,0,0,.5);
> text-rendering: optimizeLegibility;
> font-style: normal;
> direction: ltr;
> font-weight: normal;
> 
> That first font family is GalaxiePolarisCondensed-Book and would have to be imported.

Hmmm... I don't think we have that much control.

To elaborate, the HTML you see at https://distantreader.org is/was created with a front-end called Airivata, and Airivata is built on a Django framework. Airivata's primary purpose it to accept jobs, submit them to the underlying scheduling, and return status messages from the scheduler. 

--
Eric

**Comment by molikd** [comment]
I see what you're saying and unless we edited the Notre Dame image in the upper-left hand corner of the distantreader.org page to include text for the "Center for Digital Scholarship" it would be extremely difficult to put CDS branding in the upper left corner. 

I put a CDS logo in the footer for now (till we can get a better image for the top-left. 

This uses the following css:

```
.cds-logo-1 {
    font-family: GPCBook,"HelveticaNeue",Helvetica,Arial,Verdana,sans-serif;
    text-shadow: 1px 1px 1px rgba(0,0,0,.5);
    text-rendering: optimizeLegibility;
    font-style: normal;
    direction: ltr;
    font-weight: normal;
}
.cds-logo-1 a:link { 
  color: #0c2340; 
  text-decoration: none;
}
.cds-logo-1 a:visited { 
  color: #0c2340; 
  text-decoration: none;
}
.cds-logo-1 a:hover { 
  color: #0c2340; 
  text-decoration: none;
}
.cds-logo-1 a:active { 
  color: #0c2340; 
  text-decoration: none;
}
```

We can force the user to download with @font-face:

```
// This would be used to force the user to use GPCBook font. 
/*
@font-face {
  font-family: GPCBook;
  src: url(/documents/1/GalaxiePolarisCondensed-Book.otf);
}
*/
```

I'll bug natalie to get a logo for CDS like this one: 
![image](https://user-images.githubusercontent.com/9337053/79004251-6150a100-7b22-11ea-9893-de498ddf5991.png)

**Comment by molikd** [comment]
or this: ![image](https://user-images.githubusercontent.com/9337053/79006286-d58d4380-7b26-11ea-92a2-59ac73e4b70b.png)

**Comment by molikd** [comment]
okay. I added the logos this can be marked as done.

**Comment by molikd** [comment]
okay. I added the logos this can be marked as done.

see footer and top left of distantreader.org

**Comment by ericleasemorgan** [comment]
> I see what you're saying and unless we edited the Notre Dame image in the upper-left hand corner of the distantreader.org page to include text for the "Center for Digital Scholarship" it would be extremely difficult to put CDS branding in the upper left corner.

  Very nice! --Eric
