### ISSUE TITLE
Update Readme line 27

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#33]
@ericleasemorgan in [readme](https://github.com/ericleasemorgan/reader/blob/master/README.md) need to fix in link to Slack channel - http://bit.ly/distantreader-slack to slack, on line 27 of readme, no longer valid

**Comment by ericleasemorgan** [comment]
Done, and the new link to the Slack channel is http://bit.ly/distantreader-on-slack  Apparently the underlying link will not expire. "Famous last words".
