### ISSUE TITLE
improve crawl success when retrieving content against javascript sites

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#35]
If the Distant Reader is going to take single URLs or lists of URLS as input then it is important that the crawl succeeds in retrieving content from the sites.  So, we need to choose and implement a headless browser into the harvester. 

For example, the current wget crawl of the hesburgh  library URL https://library.nd.edu/covid-19-response  retrieves only: "Hesburgh Library Hesburgh Library Please enable javascript. VERSION: SHA ENV: ENVIRONMENT library-nd-edu-60906.0040517715371715 "  because the website requires javascript to be enabled in order for the website to be rendered 

Web crawlers can implement the equivalent of a headless browser engine to  render this type of content successfully. Since so many sites on the web currently utilize javascript for rendering (like React sites) if the Distant Reader uses  'wget'  alone then it won't be able to render the javascript dependent sites.There are several ways to automate the crawling of web content that requires javascript. Here is a short list of some application libraries that could be used: Selenium, Electron, Protractor, Puppeteer. The Distant Reader web crawling functionality needs to be enhanced by using a tool like this if it is going to successfully take single URLs or lists of URLs as input since  web content is often rendered in this fashion - or through using pre-rendering tools such as Gatsby.js.

**Comment by nkmeyers** [comment]
@molikd depending on your pov this is either an enhancement or a bug fix. Treat it whichever way makes sense in organizing work sprints?

**Comment by molikd** [comment]
Headless Firefox, or PhantomJS are the go tools for this. 

checkout: https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Headless_mode

however, the stupid easy way to do this, and get it done as soon as possible is through lynx (text based web browser):

`curl [-u login:pass] http://www.a_page.com | lynx -stdin -dump`

this is essentially a curl that passes everything for rendering to lynx. 

 Think about setting this up as it's own micro service, i.e. we build a quick and dirty web api that can be given a url and responds with

**Comment by molikd** [comment]
upon further thought, we can get this done right now with a bash script in the reader/bin directory, something like "urlcrawl.sh" or something, basically wrap curl and lynx and call it a day.

**Comment by ericleasemorgan** [comment]
This issue not necessary for our purposes. In this project we do not crawl remote sites to get content. Our content is given to us.
