### ISSUE TITLE
New ssh creds for development work in new deploy

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#37]
-get list of users 
-ask for public keys
-new ssh creds for development work in new deploy

**Comment by ECoulter** [comment]
List of users who need SSH access via email: Art, Charlie, Dave, Ralph, Ryan, and Shivam.
3/6 (Art, Ralph, Ryan) of these are deployed on the new cluster.

**Comment by ghost** [comment]
I have sent an email to Eric.

**Comment by ericleasemorgan** [comment]
I think this work has (more or less) been done for the folks who presently need access to the head done.
