### ISSUE TITLE
update "Cite Us" page 

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#4]
Eric,

we need to create a new citation for distant reader. The easiest way to do this if for you to create a https://zenodo.org account and link the  ericleasemorgan/reader repo to that. You can log into zenodo with your github credentials. 

-Dave

**Comment by ericleasemorgan** [comment]
> Eric we need to create a new citation for distant reader. The easiest way to do this if for you to create a https://zenodo.org account and link the ericleasemorgan/reader repo to that. You can log into zenodo with your github credentials.


All of this citation stuff is new to me. 

I have created a Zenodo account, and I believe I have created a DOI (citation) for the Reader --> 10.5281/zenodo.3748661  Now what? --Eric
