### ISSUE TITLE
Need a Distant Reader logo. 

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#40]
We require a distant reader logo so that problems like #39 do not arise. This logo will go on the landing page, and will be used on the github as well.

**Comment by nkmeyers** [comment]
Using https://distantreader.org/media/images/distant_reader.original.png  for time being - probably still need a "real logo"

**Comment by molikd** [comment]
updated distantreader.org, logo acquired, we can close this ticket.
