### ISSUE TITLE
introduce yourself to the reader

### ISSUE THREAD

**Issue by ericleasemorgan** [ericleasemorgan/reader#45]
Please use the attached file as a sort of tutorial, and through the process I think (hope), you will be introduced to the Distant Reader process. Please tell me whether nor not the process was successful. 

[tutorial-01.txt](https://github.com/ericleasemorgan/reader/files/4635752/tutorial-01.txt)

**Comment by ericleasemorgan** [comment]
I'm moving thus to a next week's "sprint". Charlie, do you think you can do this work? --Eric

**Comment by archaeocharlie** [comment]
@ericleasemorgan Yes! The past two weeks threw some unexpected things my way and now I'm finally here. Very sorry for the delay on being present with all of this.

**Comment by ericleasemorgan** [comment]
Thank you. --Eric M.
