### ISSUE TITLE
Please add a License

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#5]
Eric, 
From Natalie:
9. Make sure distant reader has a license on github if it doesn’t have one, assign one. Why? This is an essential step to making Distant reader FAIR - making sure it has a machine findable accessible license attached to the code. We use Apache V2 for Presqt use that copy of that file if you can’t decide what to use. https://github.com/ndlib/presqt/blob/master/LICENSE

Dave

**Comment by molikd** [comment]
I use MPL v2 on met, so that might make sense as well.

**Comment by ericleasemorgan** [comment]
> please add a License to the github repo. The LICENCE can be whatever you want, but please add a LICENCE file that contains that information.


  Added. I added the GNU Public License. --Eric
