### ISSUE TITLE
Write up Tickets for items in heuristic eval 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#54]
write up tickets for  any remaining suggestions in [heuristic_Evaluation_DR](https://drive.google.com/open?id=1QhTqrg_zrv60vOySKm6FEGWElnhoR6Uo)(1).pdf  and assign the tickets for implementation, related to   #32

**Comment by ericleasemorgan** [comment]
The heuristics were implemented a long time ago.
