### ISSUE TITLE
Selectively disseminate tickets

### ISSUE THREAD

**Issue by jodischneider** [ericleasemorgan/reader#55]
Identifying WHO needs to be subscribed to WHICH issue will be helpful. Current situation is "issue overload"

**Comment by molikd** [comment]
Good question, we need to develop a list of people that are working on the project, and what they are doing.

**Comment by ericleasemorgan** [comment]
On May 20, 2020, at 12:26 PM, Jodi Schneider <notifications@github.com> wrote:

> Identifying WHO needs to be subscribed to WHICH issue will be helpful. Current situation is "issue overload"

Jodi, good point, and I (we) need to practice and get used to the use of GitHub. I will update a specific task which has your name on it, and you ought to get the update. Right now, I would like you to use the existing Distant Reader interface to create one carrel, of your choice. It is to be considered practice. --ELM

**Comment by molikd** [comment]
Closing this issue in favor of #60 please reference that ticket for more succinct pushes.
