### ISSUE TITLE
Calculate a bechdel score

### ISSUE THREAD

**Issue by ralphlevan** [ericleasemorgan/reader#57]
The bechdel score rates the importance of a female in a movie. Can this be applied to other text? (Clearly this has no use in CORD data and the test should be smart enough to realize that in the corpus and short-circuit.) There are a number of examples of code to calculate a bechdel score in github. https://github.com/search?q=+bechdel+test&type=
This is super unimportant to the CORD project, but seems amusing when everything else is done

**Comment by ericleasemorgan** [comment]
These types of algorithms can be very useful, yes. By calculating them and enhancing our "bibliographic" records accordingly, we can then filter and sort results which everybody likes to do. Other algorithms include additional readability scores, something like information "gain", log likelihood ratios, etc. Actually, I wish such things were calculated against the content of traditional libraries and the MARC records where enhanced accordingly. --ELM

**Comment by ralphlevan** [comment]
looking specifically at the Pratchett collection, I'm interested in seeing if we can watch his Alzheimers progression. I've see reports where that can be measured in a writer's output

**Comment by ralphlevan** [comment]
some of the data already being generated would love some graphs over time, if we had publication dates in our metadata

**Comment by ralphlevan** [comment]
I've taken this out of sprint 6 and moved it onto the back burner (long term enhancements). While I'm interested in doing this, it's probably the lowest priority issue on our list and has no application to covid-19 research.

**Comment by ericleasemorgan** [comment]
Actually, for this specific project (Project CORD), I think this whole issue could be deleted. It is a cool idea, but not a very high priority. My 2¢.

**Comment by ericleasemorgan** [comment]
This is sincerely a cool idea, but not necessarily in the scope of our project.
