### ISSUE TITLE
re-create the Solr index

### ISSUE THREAD

**Issue by ericleasemorgan** [ericleasemorgan/reader#59]
The structure of our underlying database has evolved and been filled with new content. Consequently our Solr index needs to be re-created. Attached ought to be two files documenting the desired outcome in great detail.

[database-schema.txt](https://github.com/ericleasemorgan/reader/files/4683359/database-schema.txt)

[solr-schema.txt](https://github.com/ericleasemorgan/reader/files/4683357/solr-schema.txt)

**Comment by artunit** [comment]
The index has been recreated.

**Comment by artunit** [comment]
Just a couple more notes on this (and I think this issue could be closed). I changed the _DataImportHandler_ to be more efficient for pulling data from the databases, and compiled a slightly modified _PlainTextEntityProcessor_ to test if the file exists first. This avoids a gazillion java exception messages in the logs and makes it easier to zero in on the 15 documents out of more than 100K that were not getting processed (but made no difference in throughput, still about 28 minutes to run through the set). It looks like all of the documents that failed have a _year_ entry in the _documents_ table that is not an integer (_nan_), these could be avoided with the sql statement in the config file but it's probably good to be able to flag these (to see an example: _select year from documents where document_id=107609_). The key files are included here just to have another copy (with a _.txt_ extension added to allow them to be attached to an issue).

[DIHconfigfile.xml.txt](https://github.com/ericleasemorgan/reader/files/4691392/DIHconfigfile.xml.txt)
[solrfields.sh.txt](https://github.com/ericleasemorgan/reader/files/4691394/solrfields.sh.txt)

**Comment by ericleasemorgan** [comment]
P. S. This is a really interesting way to create Solr index. ++  We ought to figure out how to save your configuration files and scripts to the cord-19 repository.

**Comment by ericleasemorgan** [comment]
I'll close this, because I need practice too.
