### ISSUE TITLE
review administrative rights for "reader" repository

### ISSUE THREAD

**Issue by molikd** [ericleasemorgan/reader#6]
Eric, 

both Natalie ( nkmeyers ) and I should probably have administrative rights to do the following on the prime 'reader' repo: 

- and status and change status in https://github.com/ndlib/presqt/projects/1
- assign people to 'reader' tickets/issues

could you change the settings accordingly?

-Dave

**Comment by ericleasemorgan** [comment]
> both Natalie ( nkmeyers ) and I should probably have administrative rights to do the following on the prime 'reader' repo:
> 
>   • and status and change status in https://github.com/ndlib/presqt/projects/1
>   • assign people to 'reader' tickets/issues
> 
> could you change the settings accordingly?


Question #1, Dave, do you see this message? Question #2, as per above, how do I make that so? --Eric

**Comment by ericleasemorgan** [comment]
I'm not sure, but I think I have issued "invitations" to molikd and to nkmeyers, and y'all can have some sort of access. If y'all accept, then maybe you can edit the projects?
