### ISSUE TITLE
Sprint planning and enhancements - ticket-ify this stuff and stick it in sprints 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#60]
@ericleasemorgan writes: I am not ignoring y'all. Interesting discussions, and I encourage them to continue. 

Concurrently, we need to: 1) [get the whole thing running](https://github.com/ericleasemorgan/reader/milestone/6), and 2) then do enhancements. When it comes to Item 1, we have to:

  1. harvest/cache the data set (done) #13
  2. stuff the result into a database (done) #9 #12
  3. enhance the database with additional content (all but done) _- what tickets are related to this? and does any other milestone or issue completion depend on it?_
  4. index the database (all but done) #14 #15 #22 #59
  5. make it easy for Team CORD to create study carrels (half done) - _what tickets are related to this? and does any other milestone or issue completion depend on it?_ 
  6. make many carrels (barely started) - _what tickets are related to this and does any other milestone or issue completion depend on it?_ 
  7. create a Web presence (almost done) #16, #17 any others? 

**STUFF Below here needs to be ticket-ified or aligned with tickets .** 
Once we get that far, which I anticipate will be by next Friday(May 29?) , we can go for enhancements, and there are many possibilities:

  * add long titles to list of carrels 
  * allow people other than Team CORD to create study carrels
  * create a study carrel out of the whole of CORD, which requires scalability 
  * create better stop word list
  * enable the whole "library" to be re-created 
  * enhance author names with corresponding ORCHIDs
  * enhance Web presence with additional logos and attributions
  * extract additional grammars
  * figure out a way to dynamically create stop word list
  * generate additional measures of the documents
  * hyperlink bibliographic items to full text and other things
  * illustrate relationships using a network diagram
  * improve topic modeling
  * index study carrels
  * make everything FAIR
  * plot results on a map
  * plot results on a time line
  * refine entity output

As we enhance, we will repeatedly go back to Step #6 and re-build study carrels over and over, thus the carrels will be in a state of "continuous improvement".†

The whole thing is like playing guitar. First you need to learn how hold it. Then you need to learn how to tune it. Then you need to learn a few chords. After that you need to learn how to "keep time". Once you get that far, then you can concentrate to bending notes, advance to finger picking, playing syncopation, experiment with alternative tunings, moving the chords up and down the fret board, improvising, playing in various styles, performing, recording, etc.

We are getting there. I assure you. Please continue to discuss all of these things, and once we get the Reader running, we will prioritize enhancements, divvy up the work, and make the whole something we can be proud of. 

† I can't believe I actually used that phrase.

--
Eric M.

_Originally posted by @ericleasemorgan in https://github.com/ericleasemorgan/reader/issues/58#issuecomment-634150227_

**Comment by molikd** [comment]
This ticket is related to #55 going to close #55 in favor of this more succinct ticket 

here are tickets for things that you mentioned, where I could find them: 

- add long titles to list of carrels
  - #30 
- allow people other than Team CORD to create study carrels
- create a study carrel out of the whole of CORD, which requires scalability
- create better stop word list
  - #58 
- enable the whole "library" to be re-created
- enhance author names with corresponding ORCHIDs
- enhance Web presence with additional logos and attributions:
  - #29 #25 #7 #40 
- extract additional grammars
- figure out a way to dynamically create stop word list
  - #58 
- generate additional measures of the documents
- hyperlink bibliographic items to full text and other things
- illustrate relationships using a network diagram
- improve topic modeling
  - #8 #27 
- index study carrels
- make everything FAIR
- plot results on a map
- plot results on a time line
- refine entity output

**Comment by ericleasemorgan** [comment]
To the best of my ability, things have been "ticket-ified".
