### ISSUE TITLE
Add specific documentation for code contributors

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#64]
Add documentation stub for on-boarding code contributors to the Distant Reader Classic and the Distant Reader CORD19 project, recommend to do that initially as a CONTRIBUTING.md file at https://github.com/ericleasemorgan/reader/ that is linked to from README.md 

could take https://github.com/osfclient/osfclient/blob/master/CONTRIBUTING.md as an example   

or  could simply update readme.md with new sections on documentation and contributing as in example at https://github.com/cltk/cltk

Related to #62

**Comment by nkmeyers** [comment]
@ericleasemorgan or @molikd can you invite @dbrower to become a collaborator on this project because he's working on this ticket . . .

**Comment by dbrower** [comment]
I have a draft contributing here: https://github.com/dbrower/reader/blob/add-contributing/CONTRIBUTING.md

**Comment by ericleasemorgan** [comment]
Invitation sent.

**Comment by ericleasemorgan** [comment]
@dbrower , I have seen your CONTRIBUTING.md file. It is a great start. I am still learning how to do this GitHub thing. Please send me a pull request and I will addd it to the repository. Okay?

**Comment by ericleasemorgan** [comment]
Another document that may be of interest is the "manifest". Each carrel comes with one, for example:

  https://cord.distantreader.org/carrels/tiny-carrel/MANIFEST.htm

In even greater detail, the manifest outlines the contents of a study carrel.

--
ELM

**Comment by dbrower** [comment]
linking this to my pull request #78 

I was thinking, and I think I'll put all the other details from our conversation into another document. It seems like we don't want the contributing doc to get too detailed (b/c it is more likely to go out of date) or long (b/c no one will read it).

But one detail that needs to be filled out in the contributing doc are answers to the first four questions: WHO can contribute? HOW do they contribute? and HOW are does the project communicate?

**Comment by ericleasemorgan** [comment]
> But one detail that needs to be filled out in the contributing doc are answers to the first four questions: WHO can contribute? HOW do they contribute? and HOW are does the project communicate?


In this regard, are you looking for real answers from me? If so, then I don't have THE answers but I have SOME answers. Hmmm...

Who can contribute? I think the short answer is "anybody", but there are tiers of contribution. Contributors are encouraged to fork or branch the code. Hack & improve. Submit pull requests. Have requests reviewed. If successful, then things are merged. If not successful, then repeat. Once familiarity between the exiting team and the new contributor is established, the flow may be expedited. 

How to contribute? Branch or fork the code. Hack. Submit pull requests.

Communication? We have selected Slack as our communication platform. Anybody is free to join:

  http://bit.ly/distantreader-on-slack

'Make sense. Is this sort of what you expected?

--
Eric

**Comment by dbrower** [comment]
Thanks. This is mostly what i expected. I'll update the document.

**Comment by ericleasemorgan** [comment]
Done. See https://github.com/ericleasemorgan/reader/blob/master/CONTRIBUTING.md

**Comment by nkmeyers** [comment]
@ericleasemorgan or @molikd can you update the top lines of the contributing.md they currently read: 
WHO can contribute?
HOW do they contribute? code? other?
WHAT do we need contributed?
WHAT communication? issues? calls? mailing lists?

but there are no answers or links ;)

**Comment by ericleasemorgan** [comment]
After processing Don's pull request, I think these things have gone away, and an additional document has been created GUIDE.md

**Comment by dbrower** [comment]
The WHO, HOW, WHAT lines were placeholders. I revised them to provide answers and links to things, such as our slack account.
