### ISSUE TITLE
Improve named entity extraction

### ISSUE THREAD

**Issue by ericleasemorgan** [ericleasemorgan/reader#74]
**Improve named entity extraction**

Named entities are fancy nouns. Named entities may be things like "President Trump" or "World Health Organization". Depending on what sort of machine learning language model used, named entities come in different types. Examples include PERSON, ORG, LOC, TISSUE, SIMPLE-CHEMICAL, etc. We need/want to do named entity extraction against our texts and thus enhance our data set.

Presently, the program doing our named entity extraction is here:

  https://github.com/ericleasemorgan/reader/blob/master/bin/txt2ent.py

Given a plain text file, the script does its good work and outputs a stream of tab-delimited data, looking list this:

  cord-89614-a6ogjh92  226  26  Quantitative       ORG
  cord-89614-a6ogjh92  216   4  Mitteitung         PERSON
  cord-89614-a6ogjh92  217   1  Kernporen          PERSON
  cord-89614-a6ogjh92  217   2  Zellkernen kSnnen  PERSON

Your mission, if you choose to accept it, is to improve txt2ent.py so it: 1) uses additional language models, and thus 2) outputs additional named entities. For example, install and use the SciSpacy language models found here:

  https://allenai.github.io/scispacy/

In the end, we hope to extract biological entities as well as things like PERSON or LOC, but we might also want to filter the results for things which are obviously not named entities. 

The output of txt2ent.py is not allowed to change; the output still needs to be tab-delimited with the existing column names.

To do this work:

  1. download txt2ent.py
  2. get it to run, and thus you may need to install some modules
  3. edit txt2ent.py
  4. test it with sample data found at https://cord.distantreader.org/carrels/tiny-carrel/txt/
  5. if not satisfied, then go to Step 3
  6. done
  
When finished, please share txt2ent.py with Eric Morgan.

**Comment by archaeocharlie** [comment]
I just merged in an updated txt2ent that adds three scispacy language models and can take any additional models in the future.
