### ISSUE TITLE
hyperlink IDs to their fulltext in Questions "report"

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#82]
For example in https://cord.distantreader.org/carrels/SusceptibilityGender/htm/questions.htm need to hyperlink the IDs in the leftmost column to their actual full text and then do a kwic type link to their "question" within the text, so 2 steps to complete this ticket?

1. link ids to docs 
2. link questions to their kwic pair.

**Comment by ericleasemorgan** [comment]
Migrated to Issue #92
