### ISSUE TITLE
bugs in bloodtype carrel processing 

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#83]
I created a very buggy [bloodtype carrel](https://cord.distantreader.org/carrels/bloodtype/index.htm). It has no *.htm* , it is missing certain other output elements and has others, for example it has a : [noun verb report](https://cord.distantreader.org/carrels/bloodtype/htm/noun-verb.htm) 

The query to create the carrel was something like "blood type" it seems to have processed 161 records to bib as job 2545. 
at 1:12 AM  It was Slurm Job_id=2545 Name=bloodtype Began, Queued time 02:13:31 
1:42 AM Slurm Job_id=2545 Name=bloodtype Ended, Run time 00:29:28, COMPLETED, ExitCode 0 

Maybe the bugs are why the carrel took so long to run even though it only was being sent ~164 records? Distant Reader had to work pretty hard to write standard-error.txt because it is L O N G and full of errors?  

**Here are some of the processing bugs** from /export/www/html/main/carrels/bloodtype/standard-error.txt(attached). 
[standard-error.txt](https://github.com/ericleasemorgan/reader/files/4742628/standard-error.txt)
**Here's where we can see that some directories are not being written:** 
![image](https://user-images.githubusercontent.com/3044754/83976105-f1625b00-a8c5-11ea-85d7-65b13010a268.png)
**Here we can see J2KImageReader not loaded JPEG2000 files will not be processed** _(I don't know if we care about that or not?)_ 
![image](https://user-images.githubusercontent.com/3044754/83976118-0d65fc80-a8c6-11ea-8c4a-2c6580acba80.png)
**here's where we see sqlite-jdbc not loaded** _(IDK if we care about that either?)_
![image](https://user-images.githubusercontent.com/3044754/83976179-70579380-a8c6-11ea-81dd-0f95055389f1.png)
**Here's where we see the processing starting to fail against the records?**, this happens a lot - at least twice per "unfound" record, over and over 
![image](https://user-images.githubusercontent.com/3044754/83976197-941ad980-a8c6-11ea-91cc-f52231ce4ef4.png)
![image](https://user-images.githubusercontent.com/3044754/83976247-dc39fc00-a8c6-11ea-94f5-870a8433b6d0.png)
**Then a new kind of error ?** 
![image](https://user-images.githubusercontent.com/3044754/83976282-13a8a880-a8c7-11ea-9749-fc67fb023942.png)
**starts failing stuff on txt2ent.py bcs too long for the parser and NER model defaults?**
![image](https://user-images.githubusercontent.com/3044754/83976328-5b2f3480-a8c7-11ea-8d95-f8b0682de9a6.png)
**Some stuff doesn't get written because the parser or NER scripts can't run bcs some files are over the default in size?** 
![image](https://user-images.githubusercontent.com/3044754/83976374-8b76d300-a8c7-11ea-8e68-917f800d6ef5.png)
**and other stuff doesn't get written for same reasons?** 
![image](https://user-images.githubusercontent.com/3044754/83976390-9e89a300-a8c7-11ea-93e5-482c9dcf701d.png)

**Comment by ericleasemorgan** [comment]
This "bug" was probably caused by the unavailablity of a metadata file, and that is because the carrel creation process exited prematurely. I recreated the bloodtype carrel, and it functions. This probably won't happen again. Signed by "Famous Last Words".
