### ISSUE TITLE
Keep user in cord.distantreader.org  on carrels navigation

### ISSUE THREAD

**Issue by nkmeyers** [ericleasemorgan/reader#86]
On [https://cord.distantreader.org/carrels/](https://cord.distantreader.org/carrels/) update the link from distantreader logo etc so the user "stays" in cord.distantreader.org instead of getting punted out to distantreader.org ? 

And figure out another UI way for the user to get back to  cord "carrels" instead of getting punted over to distantreader.org after clicking into a cord carrel page from  [https://cord.distantreader.org/carrels/](https://cord.distantreader.org/carrels/)? 

Good time to swap in the new DR  logo & banner too? they're at: [https://github.com/ericleasemorgan/reader/issues/25](https://github.com/ericleasemorgan/reader/issues/25)

**Comment by ericleasemorgan** [comment]
Added to #73
